version: '3.8'

services:

  nextjs:
    container_name: nextjs_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MONGODB_URI=mongodb://admin:password@mongodb:27017
    depends_on:
      - mongodb
    networks:
      - app_network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-myapp}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

volumes:
  mongodb_data:
    name: mongodb_data

networks:
  app_network:
    driver: bridge